# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='linked_object_id',
        ),
    ]
