# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0003_post_linked_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='associated_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='associated_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_associated_type', to='contenttypes.ContentType'),
        ),
    ]
