# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connection_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='state',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('W', 'Withdrawn'), ('B', 'Blocked')], default='P', max_length=1),
        ),
    ]
