# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_media_has_quiz'),
        ('module_progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='current_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Media'),
        ),
    ]
