# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_progress', '0002_moduleprogress_current_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='percent_completed',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
