# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_progress', '0003_moduleprogress_percent_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprogress',
            name='percent_completed',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
