# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_progress', '0004_auto_20160427_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='assessment_submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='has_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
