# -*- coding: utf-8 -*-
# Generated by Django 1.9c2 on 2016-01-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(default='#014386', max_length=50),
        ),
    ]
