# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_userassessment_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_userassessment_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name_plural': 'Modules'},
        ),
        migrations.AddField(
            model_name='module',
            name='has_user_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='user_assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.UserAssessment'),
        ),
    ]
