# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20160428_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='group_assessment',
            field=models.BooleanField(default=False),
        ),
    ]
