# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_userassessment_group_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='user_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module.UserAssessment'),
        ),
    ]
