# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_module_sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionvideocontainer',
            name='order',
        ),
    ]
