# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_module_sections', '0002_remove_sectionvideocontainer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionvideocontainer',
            name='vimeo_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
