# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_module_sections', '0003_sectionvideocontainer_vimeo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_container',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
