# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_module_sections', '0004_auto_20170323_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionimage',
            name='src',
        ),
    ]
