# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170323_2037'),
        ('course_module_sections', '0005_remove_sectionimage_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontext',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
