# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 14:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_gallery_galleryimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_module_sections', '0009_auto_20170407_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField(blank=True)),
                ('html', models.TextField(blank=True, help_text='This is auto generated from Text.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_module_sections_sectiongallery_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Gallery')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_module_sections_sectiongallery_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sectionassessment',
            name='html',
            field=models.TextField(blank=True, help_text='This is auto generated from Text.'),
        ),
        migrations.AddField(
            model_name='sectionattachment',
            name='html',
            field=models.TextField(blank=True, help_text='This is auto generated from Text.'),
        ),
        migrations.AddField(
            model_name='sectionimage',
            name='html',
            field=models.TextField(blank=True, help_text='This is auto generated from Text.'),
        ),
        migrations.AddField(
            model_name='sectionvideocontainer',
            name='html',
            field=models.TextField(blank=True, help_text='This is auto generated from Text.'),
        ),
    ]
