# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0001_initial'),
        ('course_module_sections', '0011_auto_20170629_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSurveyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField(blank=True, help_text='Markdown can be used here.')),
                ('html', models.TextField(blank=True, help_text='This is auto generated from Text.')),
                ('textColor', models.CharField(blank=True, default='', max_length=255)),
                ('backgroundColor', models.CharField(blank=True, default='', max_length=255)),
                ('survey_group', models.UUIDField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_module_sections_sectionsurveygroup_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_module_sections_sectionsurveygroup_modified_by_related', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
