# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20160413_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='parent_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Media'),
        ),
    ]
