# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacategory',
            name='color',
            field=models.CharField(default='#014386', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='image',
            field=models.FileField(null=True, upload_to='media_images/'),
        ),
    ]
