# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20160413_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media_images/'),
        ),
    ]
