# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20160420_1125'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.Module'),
        ),
        migrations.RemoveField(
            model_name='media',
            name='category',
        ),
        migrations.AlterOrderWithRespectTo(
            name='media',
            order_with_respect_to='module',
        ),
        migrations.DeleteModel(
            name='MediaCategory',
        ),
    ]
