# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20160420_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='parent_media',
        ),
    ]
