# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_media_has_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('order',), 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='media',
            order_with_respect_to=None,
        ),
    ]
