# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        ('media', '0011_auto_20160421_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_quiz', to='quiz.Quiz'),
        ),
    ]
