# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileexperience',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
