# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_experience', '0003_auto_20170425_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileexperience',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
