# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import images.models
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, storage=storages.backends.s3boto.S3BotoStorage(acl='private', bucket='twz-dev'), upload_to=images.models.content_file_name, width_field='width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
