# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20170517_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': ['Galleries']},
        ),
    ]
