# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20170615_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.CharField(default='rgb(255,255,255)', max_length=20),
        ),
    ]
