# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 16:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_image_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='face_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
