# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_image_face_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='display_position',
            field=models.CharField(default='center', max_length=10),
        ),
    ]
