# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170525_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=3),
        ),
    ]
