# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 15:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('course_module_sections', '0010_auto_20170517_1448'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_course_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('object', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('ended', models.BooleanField(default=False)),
                ('ended_on', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('total_time_viewing', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_courseprogress_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('current_course_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseModule')),
                ('current_course_module_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_module_sections.CourseModuleSection')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_courseprogress_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
