# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 21:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='last_opened',
            field=models.DateTimeField(default=timezone.datetime.now, editable=False),
        ),
    ]
