# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170616_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='vimeo_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='watches',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
