# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
