# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 19:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0012_image_display_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='LESubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('versions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[])),
                ('description', models.TextField(blank=True, help_text='This is a short description of the LE.')),
                ('markdown', models.TextField(blank=True, help_text='The plain text markdown.')),
                ('html', models.TextField(blank=True, help_text='The html.')),
                ('number_of_ratings', models.IntegerField(blank=True, default=0, null=True)),
                ('average_rating', models.IntegerField(blank=True, default=None, null=True)),
                ('average_ratings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('approved', models.BooleanField(default=False)),
                ('approved_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('submited', models.BooleanField(default=False)),
                ('submited_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_experience_submissions_lesubmission_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_experience_submissions_lesubmission_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LESubmissionRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.TextField(blank=True, help_text="The reviewer's comments.")),
                ('approved', models.BooleanField(default=False)),
                ('ratings', django.contrib.postgres.fields.jsonb.JSONField(default={'Accessibility': 1, 'Conciseness': 1, 'Grammar, Spelling': 1, 'Immersiveness': 1, 'Style': 1, 'Technical Overview': 1})),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_experience_submissions_lesubmissionrating_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('le_submission', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='learning_experience_submissions.LESubmission')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_experience_submissions_lesubmissionrating_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
