# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_experience_submissions', '0002_lesubmissionrating_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesubmission',
            old_name='submited',
            new_name='submitted',
        ),
        migrations.RenameField(
            model_name='lesubmission',
            old_name='submited_on',
            new_name='submitted_on',
        ),
    ]
