# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 23:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('groups', django.contrib.postgres.fields.jsonb.JSONField(default=[{'description': 'this is a group description, not required.', 'questions': [{'answers': [{'title': 'Yes'}, {'title': 'No'}], 'question': 'This is a boolean question', 'type': 'radio', 'uuid': '77fcb271-8718-413c-8a31-10d7aa0dd960'}, {'answers': [{'title': 'Very much'}, {'title': 'No at all'}, {'title': 'Impartial'}, {'title': 'Enter small text here'}, {'title': 'Other'}], 'question': 'This is a multiple choice with other question', 'type': 'radio-with-other', 'uuid': '3533584e-cb6e-422f-b2c5-5aadb1887c7b'}], 'title': 'This is a group title', 'uuid': '4663b60c-9555-4761-a8a4-f8a45dbb46a2'}, {'description': 'this is a group description, not required.', 'questions': [{'answers': None, 'question': 'This is a free form text area question', 'type': 'longtext', 'uuid': '61fdae77-918c-4f4c-9ae6-0b9800a7a15b'}, {'answers': [{'title': 'It works'}, {'title': 'It is green'}, {'title': 'Swiping'}, {'title': 'Social Feed'}], 'question': 'What is most the important features to you?', 'type': 'checkbox', 'uuid': 'a2ebf7aa-f68b-486a-80aa-d054879f0e7d'}, {'answers': [{'title': 'It works'}, {'title': 'It is green'}, {'title': 'Swiping'}, {'title': 'Social Feed'}, {'title': 'Other'}], 'question': 'What is most the important features to you?', 'type': 'checkbox-wth-other', 'uuid': '7be87e2b-4169-46e0-8d4b-2f9ff9f88773'}, {'answers': None, 'question': 'How important is getting a job to you?', 'scale': [1, 5], 'type': 'scale', 'uuid': 'f72e7a64-f912-4965-b4e3-fda274099571'}, {'answers': None, 'question': 'This is a short text question?', 'type': 'shorttext', 'uuid': '0a2eec3b-241b-4b71-a081-5a382af81434'}], 'title': 'This is a group title', 'uuid': '1a7e7f13-e765-4ae3-9196-63d9e5e40702'}])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys_survey_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys_survey_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('answer_data', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys_surveyresponse_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys_surveyresponse_modified_by_related', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
