# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0002_auto_20170322_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
