# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0004_auto_20170517_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_country_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
