# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0006_phoneverificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneverificationcode',
            old_name='used',
            new_name='is_used',
        ),
    ]
