# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0008_pushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
