# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0010_auto_20170621_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushtoken',
            name='device_os',
        ),
        migrations.RemoveField(
            model_name='pushtoken',
            name='device_serial',
        ),
    ]
