# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0011_auto_20170621_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='device_manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='device_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='device_version',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
