# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0013_auto_20170621_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='push_group',
            field=models.CharField(default='tw_prod', max_length=10),
        ),
    ]
