# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def fill_mymodel_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    notification_model = apps.get_model('drf_users', 'PushToken')
    for obj in notification_model.objects.using(db_alias).all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0014_pushtoken_push_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_mymodel_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pushtoken',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, unique=True),
        ),
    ]
