# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0015_uuid_on_push_token'),
    ]

    operations = [
        migrations.RemoveField('PushToken', 'id'),
        migrations.RenameField(
            model_name='pushtoken',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False, unique=True),
        ),
    ]
