# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0016_uuid_on_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
