# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_users', '0018_pushtoken_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
