# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('answer', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_quizquestionanswer_created_by_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_quizquestionanswer_modified_by_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='quizanswerquestion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quizanswerquestion',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='quizanswerquestion',
            name='quiz_question',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizQuestionAnswer'),
        ),
        migrations.DeleteModel(
            name='QuizAnswerQuestion',
        ),
        migrations.AddField(
            model_name='quizquestionanswer',
            name='quiz_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.QuizQuestion'),
        ),
    ]
