# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20170324_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='instructions_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
