# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20160126_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_on']},
        ),
    ]
