# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:38
from __future__ import unicode_literals

import attachments.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('size', models.DecimalField(blank=True, decimal_places=2, help_text='Size of file in bytes', max_digits=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(max_length=255, upload_to=attachments.models.attachment_location)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_attachment_related_ct', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
