# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20170322_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
